server:
  port: 8764

spring:
  application:
    name: feign-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true #feign开启hystrix支持
  okhttp:
    enabled: true

hystrix:
  command:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 500 #线程超时,调用Fallback方法
    circuitBreaker:
      requestVolumeThreshold: 3  #10秒内出现3个以上请求(已临近阀值),并且出错率在50%以上,开启断路器.断开服务,调用Fallback方法